
# Horiuchi's decomposition

# It takes approximately 1.5 days to run

rm(list=ls())
options(scipen=999) 

library(tidyverse)
library(openxlsx)
library(DemoDecomp)


## Table with cause-specific mortality rates

ordem_ibge <- c(
  "Brasil",
  "Norte",
  "Rondônia", "Acre", "Amazonas", "Roraima", "Pará", "Amapá", "Tocantins",
  "Nordeste",
  "Maranhão", "Piauí", "Ceará", "Rio Grande do Norte", "Paraíba",
  "Pernambuco", "Alagoas", "Sergipe", "Bahia",
  "Sudeste",
  "Minas Gerais", "Espírito Santo", "Rio de Janeiro", "São Paulo",
  "Sul",
  "Paraná", "Santa Catarina", "Rio Grande do Sul",
  "Centro-Oeste",
  "Mato Grosso do Sul", "Mato Grosso", "Goiás", "Distrito Federal"
)


tabua    <- readRDS("taxas.rds", refhook = NULL) %>%    # This file is generated by the 1_MortalityRates script
         mutate(ANO = as.numeric(as.character(ANO)),
         LOCAL = factor(LOCAL, levels = ordem_ibge))


anos <- sort(unique(tabua$ANO))
anos <- anos[anos < max(anos)]  
sexos <- unique(tabua$SEXO)
local <- unique(tabua$LOCAL)


#####################################################################################
##########              Decomposition loop                                        ###
#####################################################################################



lista_resultado_idade <- list()
lista_resultado_total <- list()


contador <- 1 

t1 <- Sys.time()
t1

for (n in anos){
  for (z in local){
    for (i in sexos){
      
      ano_base <- as.numeric(as.character(n))
      
      message("Processando ANO = ", ano_base,", LOCAL = ", z, ", SEXO = ", i)
      print(Sys.time())
      
      # Filter data for the two comparison years, selected sex, and selected location
      
      tabua_ano1 <- tabua %>% filter(LOCAL == z & SEXO == i & ANO == ano_base)     %>% select(LOCAL, SEXO, GRUPO_IDADE, Categoria.CID, taxa_morte_i1 = TAXA_MORTALIDADE)
      tabua_ano2 <- tabua %>% filter(LOCAL == z & SEXO == i & ANO == ano_base + 1) %>% select(LOCAL, SEXO, GRUPO_IDADE, Categoria.CID, taxa_morte_i2 = TAXA_MORTALIDADE)
      
      # Extract the causes of death observed in the two comparison years
      
      tabua_temp <- tabua_ano1 %>%           # Ensure that the vectors have the same ordering of causes of death
        left_join(tabua_ano2, by = c("LOCAL", "SEXO", "GRUPO_IDADE", "Categoria.CID"))
      
      pars1 <- as.vector(tabua_temp$taxa_morte_i1) # Vector of cause-specific mortality rates for Year 1
      pars2 <- as.vector(tabua_temp$taxa_morte_i2) # Vector of cause-specific mortality rates for Year 2
      
      
      # Function to calculate e0 from a concatenated nMx vector (used in the Horiuchi loop)
      
      e0_from_causeMx <- function(pars) {
        
        nMx_mat <- matrix(pars, ncol = 20, byrow = TRUE)  # Causes of death, each with 20 age groups (0,1,5,10,..,85,90)
        nMx_total <- colSums(nMx_mat)                     # Sum causes of death by age group
        
        lt <- LTabr(Mx = nMx_total, 
                    Age = c(0, 1, cumsum(rep(5, length(nMx_total) - 2))), 
                    radix = 1e5)
        
        return(lt)    # life expectancy at birth
        
      }
      
      # Decomposition
      
      contrib_total <- horiuchi(func = e0_from_causeMx,
                                pars1 = pars1,
                                pars2 = pars2,
                                N = 20)
      
      # Results
      
      resultado_idade <- data.frame(
        ANO         = ano_base +1,
        LOCAL       = z,
        SEXO        = i,
        CAUSA       = tabua_temp$Categoria.CID,
        GRUPO_IDADE = tabua_temp$GRUPO_IDADE,
        VALOR       = contrib_total
      )
      
      resultado_total <- resultado_idade %>% 
        group_by(ANO, LOCAL, SEXO, CAUSA) %>% 
        summarize(VALOR = sum(VALOR)) %>% 
        ungroup()
      
      lista_resultado_idade[[contador]] <- resultado_idade
      lista_resultado_total[[contador]] <- resultado_total
      
      contador <- contador + 1
      
      print(Sys.time())
      
    }
  }
}

t2 <- Sys.time()
t2 - t1


df_idade <- bind_rows(lista_resultado_idade)
df_total <- bind_rows(lista_resultado_total) %>% mutate(GRUPO_IDADE = "Total")


df_completo <- rbind(df_idade, df_total) %>% 
  pivot_wider(names_from = "ANO", values_from = "VALOR") %>% 
  mutate(LOCAL = factor(LOCAL, levels = ordem_ibge)) %>% 
  arrange(SEXO, LOCAL, CAUSA) 

write.xlsx(df_completo,"df_decomposicao.xlsx")

